extend: s.yaml
# 镜像 函数
services:
  fc-cloudreve: # 业务名称/模块名称
    component: fc # 组件名称，Serverless Devs 工具本身类似于一种游戏机，不具备具体的业务能力，组件类似于游戏卡，用户通过向游戏机中插入不同的游戏卡实现不同的功能，即通过使用不同的组件实现不同的具体业务能力
    actions: # 自定义执行逻辑，关于actions 的使用，可以参考：https://www.serverless-devs.com/serverless-devs/yaml#行为描述
      pre-deploy: # 在deploy之前运行
        - component: fc build --use-docker --dockerfile ./code/cloudreve/Dockerfile --context ./code/cloudreve
           # - run: docker build xxx            # 要执行的系统命令，类似于一种钩子的形式
           #   path: ./src                      # 执行系统命令/钩子的路径
    props: # 组件的属性值
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: "cloudreve_container" # 函数名
        description: 这是一个 cloudreve container 案例
        timeout: 60
        memorySize: 128
        cpu: 0.05
        diskSize: 512
        instanceConcurrency: 5
        caPort: 5212
        runtime: custom-container
        codeUri: ./
        customContainerConfig:
          image: ${env(image_url)}
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
              - PATCH
# END
        